# mk-hpa.yml
# HPA configuration file
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: community-sphere-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: community-sphere
  minReplicas: 1  # Adjust based on your requirements
  maxReplicas: 10  # Adjust based on your requirements
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Adjust based on your requirements
